### ISSUE TITLE
Chrome extension privacy permissions too broad?

### ISSUE THREAD

**Issue by adambreen** [joeltg/visual_history#1]
Is "Read and change all your data on the websites you visit" really necessary?
![screen shot 2015-12-15 at 8 52 44 pm](https://cloud.githubusercontent.com/assets/905928/11808718/f13bd4ba-a36d-11e5-910d-4a02eeb373d5.jpeg)

**Comment by joeltg** [comment]
Visual History's popup is just html injected into the page, which Google views as "reading and changing all the data on websites you visit". That warning is even triggered whenever there's a content script that matches all [all urls](https://developer.chrome.com/extensions/permission_warnings#warnings), regardless of whether the extension actually uses it or not.

I agree that it's misleadingly broad, which is one of the reasons this is open-source.

A possible alternative would be using the [activeTabs](https://developer.chrome.com/extensions/activeTab) permissions, but I think that wouldn't let the extension track tab info unless the user generate some request on that page. I'll look into it.

**Comment by mohanraj-r** [comment]
This would great to have. 
Would it be possible to get all the required tab info by just requesting permissions on `history` ?

**Comment by kennethshawfriedman** [comment]
Unfortunately, `history` doesn't provide enough information to provide a tree structure of a user's browsing history. For a given page, the extension needs to know the parent page (that is, which site the user was on when they went to the next page). Because a `history` only provides a chronologically linear list of sites (which this extension aims to enhance), there's no way to gather that information from `history` alone.

**Comment by mohanraj-r** [comment]
Thanks for the prompt response. 

Looking at [chrome.history API](https://developer.chrome.com/extensions/history) the `VisitItem` object has the property `referringVisitId` which is "The visit ID of the referrer.". Coupling this with [TransitionType](https://developer.chrome.com/extensions/history#type-TransitionType) wouldn't it be possible to get info on the parent page.

**Comment by joeltg** [comment]
So there are three possible ways to update internal state with the Chrome extension API, each of which have pros and cons, particularly relating to a few key edge cases.

Relevant APIs
- `history`: tracking `history.onVisited` events
- `webNavigation`: tracking `webNavigation.onCommitted` events
- `tabs`: listening for updates to `tab.url` in `tabs.onUpdated`

Edge cases
- Server redirects (eg auto-corrected Wikipedia links or Google search results)
  - only `webNavigation` does this right
- Instant tabs (where the content is loaded in a shadow tab with no 'referrer', and then replaced)
  - `history` can't track `onTabReplaced` events
- Custom history state manipulation (eg React Router or the Issues/PR tabs on GitHub repos)
  - `history` misses this, but `tabs` does it naturally and `webNavigation` has an `onHistoryStateUpdated` event that catches it

Since the `tabs` permission was already necessary for injecting the html for the overlay, and since the `tabs.onUpdated` was by far the cleanest to implement, I decided to prioritize simplicity by keeping it.

Personally, I'd love to ditch the html injection altogether and have the whole interface in a popup from the browser item, at which point we could move state to the `history` or `webNavigation` API to get rid of the "read and change all websites" warning, but until [this](https://bugs.chromium.org/p/chromium/issues/detail?id=436489) feature get added in Chrome we're stuck with html injection via `tabs`, and since we're already declaring `tabs` it seems best to also use that for tracking history, as opposed to adding another permission for that.

However, if there is a compelling case as to why `history` (or `webNavigation`) would be better, I'd love to hear it (or review pull requests!).
